version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: crud-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678